/**
 * Glob patterns for workspace file watchers that should trigger
 * `workspace/didChangeWatchedFiles` notifications.
 *
 * These include source files and a small set of build/framework/config inputs
 * that can affect Nova's project model and diagnostics.
 */

export const NOVA_CONFIG_REL_PATH = '.nova/config.toml' as const;
export const NOVA_APT_GENERATED_ROOTS_SNAPSHOT_REL_PATH = '.nova/apt-cache/generated-roots.json' as const;
export const NOVA_GRADLE_SNAPSHOT_REL_PATH = '.nova/queries/gradle.json' as const;

export const NOVA_CONFIG_GLOB = NOVA_CONFIG_REL_PATH;
export const NOVA_APT_GENERATED_ROOTS_SNAPSHOT_GLOB = NOVA_APT_GENERATED_ROOTS_SNAPSHOT_REL_PATH;
export const NOVA_GRADLE_SNAPSHOT_GLOB = NOVA_GRADLE_SNAPSHOT_REL_PATH;

const BUILD_SYSTEM_GLOB_PATTERNS = [
  // Maven build configuration / wrapper.
  '**/pom.xml',
  '**/mvnw',
  '**/mvnw.cmd',
  '**/.mvn/wrapper/maven-wrapper.properties',
  '**/.mvn/wrapper/maven-wrapper.jar',
  '**/.mvn/extensions.xml',
  '**/.mvn/maven.config',
  '**/.mvn/jvm.config',

  // Gradle build configuration (Groovy + Kotlin DSL) / wrapper.
  // Explicit top-level markers (required for basic Gradle project detection).
  '**/build.gradle',
  '**/build.gradle.kts',
  '**/settings.gradle',
  '**/settings.gradle.kts',
  // Script plugins / shared Gradle configuration can live anywhere.
  '**/*.gradle',
  '**/*.gradle.kts',
  // Gradle dependency lockfiles can affect resolved classpaths without modifying build scripts.
  '**/gradle.lockfile',
  '**/dependency-locks/**/*.lockfile',
  '**/gradle.properties',
  // Gradle wrapper scripts should only be treated as build inputs at the workspace root (this
  // matches Gradle build-file fingerprinting semantics in `nova-build-model`).
  'gradlew',
  'gradlew.bat',
  '**/gradle/wrapper/gradle-wrapper.properties',
  '**/gradle/wrapper/gradle-wrapper.jar',
  // Gradle version catalogs can define dependency versions.
  //
  // Keep semantics aligned with Gradle build-file fingerprinting (`nova-build-model`), which:
  // - always includes the conventional `libs.versions.toml`
  // - includes additional catalogs only when they are direct children of a `gradle/` directory
  //   (to avoid treating random `*.versions.toml` files elsewhere in the repo as build inputs).
  '**/libs.versions.toml',
  '**/gradle/*.versions.toml',

  // Bazel build configuration.
  '**/WORKSPACE',
  '**/WORKSPACE.bazel',
  '**/MODULE.bazel',
  '**/MODULE.bazel.lock',
  '**/BUILD',
  '**/BUILD.bazel',
  '**/*.bzl',
  '**/.bazelrc',
  '**/.bazelrc.*',
  '**/.bazelversion',
  '**/bazelisk.rc',
  '**/.bazelignore',
  // Bazel BSP server discovery uses `.bsp/*.json` connection files (optional).
  '**/.bsp/*.json',

  // JPMS. `module-info.java` affects module-graph classification (classpath vs module-path).
  '**/module-info.java',
] as const;

const FRAMEWORK_CONFIG_GLOB_PATTERNS = [
  // Shared framework config files that influence diagnostics and completion.
  //
  // Spring Boot / Micronaut / Quarkus commonly use `application*.properties|yml|yaml`.
  '**/application*.properties',
  '**/application*.yml',
  '**/application*.yaml',
  // MicroProfile / Quarkus config file (commonly located under `META-INF/`).
  '**/microprofile-config.properties',
  // Spring Boot configuration metadata generated by the config processor.
  '**/META-INF/spring-configuration-metadata.json',
  '**/META-INF/additional-spring-configuration-metadata.json',
] as const;

const NOVA_CONFIG_GLOB_PATTERNS = [
  // Nova workspace config.
  '**/nova.toml',
  '**/.nova.toml',
  '**/nova.config.toml',
  NOVA_APT_GENERATED_ROOTS_SNAPSHOT_GLOB,
  // `nova-build` -> `nova-project` file-based Gradle snapshot handoff.
  NOVA_GRADLE_SNAPSHOT_GLOB,
  // Legacy workspace-local config (kept for backwards compatibility).
  NOVA_CONFIG_GLOB,
] as const;

const WATCHED_FILE_GLOB_PATTERNS = [
  // Java source files.
  '**/*.java',
  ...BUILD_SYSTEM_GLOB_PATTERNS,
  ...FRAMEWORK_CONFIG_GLOB_PATTERNS,
  ...NOVA_CONFIG_GLOB_PATTERNS,
] as const;

const BUILD_FILE_GLOB_PATTERNS = [...BUILD_SYSTEM_GLOB_PATTERNS, ...NOVA_CONFIG_GLOB_PATTERNS] as const;

export function getNovaBuildFileGlobPatterns(): string[] {
  return [...BUILD_FILE_GLOB_PATTERNS];
}

export function getNovaWatchedFileGlobPatterns(): string[] {
  // Return a copy so callers can't mutate our module-level constant.
  return [...WATCHED_FILE_GLOB_PATTERNS];
}
